// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfsxjuspmolqhbnohyew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmc3hqdXNwbW9scWhibm9oeWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTI0MDAsImV4cCI6MjA2MzQ4ODQwMH0.33LcN81NGWz0EIo8ul5c9IwkppMVbwxdrFhuQd2wI4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
